[ship]
modules = ["com.hx.m2", "com.hx.n3", "com.hx.r8", "wire.alpha"]
inactive = ["wire.beta"]

[field]
modules = ["com.hx.m2", "com.hx.n3", "com.hx.r8", "wire.beta"]
inactive = ["wire.alpha"]

[default]
active = []
inactive = ["wire.alpha", "wire.beta"]
