# Packing policy: archive mode follows legacy notes; probe mode honors -DPACK_WIDTH.
set(_HOOK "/app/ops/nx/hook_q.toml")
set(_XV_MODE "probe")
if(EXISTS "${_HOOK}")
  file(STRINGS "${_HOOK}" _hook_lines)
  foreach(_line IN LISTS _hook_lines)
    if(_line MATCHES "^[ \t]*mode[ \t]*=[ \t]*\"?([A-Za-z0-9_]+)\"?")
      set(_XV_MODE "${CMAKE_MATCH_1}")
    endif()
  endforeach()
endif()

if(_XV_MODE STREQUAL "archive")
  set(_LEGACY_NOTES "/app/link/legacy.toml")
  if(EXISTS "${_LEGACY_NOTES}")
    file(STRINGS "${_LEGACY_NOTES}" _legacy_lines)
    foreach(_line IN LISTS _legacy_lines)
      if(_line MATCHES "^[ \t]*archive_pack[ \t]*=[ \t]*(.+)$")
        set(PACK_WIDTH "${CMAKE_MATCH_1}")
        set(_FROM_ARCHIVE 1)
      endif()
    endforeach()
  endif()
  if(NOT DEFINED _FROM_ARCHIVE)
    set(_FROM_ARCHIVE 0)
  endif()
  if(_FROM_ARCHIVE)
    message(STATUS "c6 packing pinned from archive notes: ${PACK_WIDTH}")
  endif()
else()
  if(NOT DEFINED PACK_WIDTH)
    set(PACK_WIDTH 8)
  endif()
  set(_PW "${PACK_WIDTH}")
  if(_PW STREQUAL "")
    set(_PW 8)
  endif()
  if(_PW LESS 1)
    set(_PW 8)
  endif()
  set(PACK_WIDTH "${_PW}")
  set(_FROM_ARCHIVE 0)
endif()
